=== opendi-org/api-specification/docs/assets/files/Causal-Decision-Model-829419545fcbb12dd4771eaf97650ae5.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://opendi.org/json-schema/v0-draft-0325/Causal-Decision-Model.json",
    "title": "Causal Decision Model",
    "description": "(DRAFT) -- Represents a Causal Decision Model for OpenDI-compliant software.",
    "properties": {
        "$schema": {
            "title": "JSON Schema URI",
            "description": "URI for schema, used for validation. Likely a URL to the public source file for this schema.",
            "type": "string"
        },
        "meta": {
            "title": "Asset Metadata",
            "description": "Metadata shared by all DI Assets",
            "$ref": "./DI-Asset.json"
        },
        "runnableModels": {
            "title": "Runnable Decision Models List",
            "description": "List containing the runnable model (or set of model components) used for computing or simulating this CDM.",
            "type": "array",
            "items": {
                "$ref": "./DI-Runnable-Model.json"
            }
        },
        "diagrams": {
            "title": "Model Diagrams List",
            "description": "List of diagrams (likely Causal Decision Diagrams) associated with this model.",
            "type": "array",
            "items": {
                "$ref": "./DI-Diagram.json"
            }
        },
        "evaluatableAssets": {
            "title": "Evaluatable Assets List",
            "description": "List of all Evaluatable Assets attached to this model. May be used by one or more Runnable Models.",
            "type": "array",
            "items": {
                "oneOf": [
                    {"$ref": "./DI-Evaluatable-Assets.json#/$defs/script"},
                    {"$ref": "./DI-Evaluatable-Assets.json#/$defs/apicall"}
                ]
            }
        },
        "inputOutputValues": {
            "title": "Input/Output Values List",
            "description": "List of all Input/Output values used by Runnable Models in this CDM. I/O Values can be read or set by Runnable Models, and interactively in Diagrams, via Controls. A single I/O Value can be referenced in multiple Runnable Models and Controls.",
            "type": "array",
            "items": {
                "$ref": "./DI-IO-Value.json"
            }
        },
        "controls": {
            "title": "Controls List",
            "description": "List of all DI Controls for this model. Controls connect I/O values to Diagram Elements, allowing values to be set or displayed.",
            "type": "array",
            "items": {
                "$ref": "./DI-Control.json"
            }
        },
        "addons": {
            "title": "Addon Data",
            "description": "Holds addon objects for storing data not specified in OpenDI standards.",
            "$ref": "./DI-Addons.json"
        }
    },
    "required": ["meta"],
    "additionalProperties": false
}

=== opendi-org/api-specification/docs/api-source/schemas/test-data.json
{
    "$schema": "./Causal-Decision-Model.json",
    "meta": {
        "uuid": "db1ae176-6734-4883-aa6e-96f9579d2f59",
        "name": "Test CDD - Word Combination",
        "summary": "CDD for testing controls: Text input and Boolean input",
        "documentation": {
            "content": "",
            "MIMEType": "text/plain"
        },
        "version": "0.1",
        "draft": true,
        "updatedDate": "2025-03-19T08:33:30-04:00",
        "createdDate": "2025-03-17T08:33:30-04:00"
    },
    "runnableModels": [
        {
            "meta": {
                "uuid": "a0ae9206-043c-4498-bc07-e52bb3acb62d",
                "name": "Example runnable model: Combine strings"
            },
            "elements": [
                {
                    "meta": {
                        "uuid": "509dd4cd-793f-4803-b401-13bbdb0aa1d4",
                        "name": "Word_12"
                    },
                    "inputs": [
                        "32e271b2-29b1-47ab-b896-68109b50cf8d",
                        "08fd2f58-9f16-4864-be4c-5a508afd7e08",
                        "c424d96a-c33c-4d35-bf31-bd0eddbf0ec9"
                    ],
                    "outputs": [
                        "bcc5cf31-b331-4de8-82d1-ea656c0961f0"
                    ],
                    "functionName": "combineStrings",
                    "evaluatableAsset": "3078afd4-cdb1-4be1-8c9a-99b80d7b85a3"
                },
                {
                    "meta": {
                        "uuid": "420a1e55-cc82-460b-8803-21cf931e908b",
                        "name": "Word_34"
                    },
                    "inputs": [
                        "1b3fb9e7-a687-45ff-85d5-6509af926e28",
                        "9d621de0-b56e-4ab1-ace0-6fdab7b3e654",
                        "c464d0b9-6cd0-4198-b6ab-79c3bd7b27f9"
                    ],
                    "outputs": [
                        "da30c2db-4ee6-49de-85d4-e53a2cdcd44d"
                    ],
                    "functionName": "combineStrings",
                    "evaluatableAsset": "3078afd4-cdb1-4be1-8c9a-99b80d7b85a3"
                },
                {
                    "meta": {
                        "uuid": "4644c2ef-b426-44e5-97bd-14ebe5c1b141",
                        "name": "Word_1234"
                    },
                    "inputs": [
                        "7ad959dd-79cb-446e-86c3-541a237c48f0",
                        "bcc5cf31-b331-4de8-82d1-ea656c0961f0",
                        "da30c2db-4ee6-49de-85d4-e53a2cdcd44d"
                    ],
                    "outputs": [
                        "3756b8f4-03a5-4e9c-9dcd-05557593bb39"
                    ],
                    "functionName": "combineStrings",
                    "evaluatableAsset": "3078afd4-cdb1-4be1-8c9a-99b80d7b85a3"
                }
            ]
        }
    ],
    "evaluatableAssets": [
        {
            "meta": {
                "uuid": "3078afd4-cdb1-4be1-8c9a-99b80d7b85a3",
                "name": "String combine script"
            },
            "evalType": "Script",
            "content": {
                "script": "KGZ1bmN0aW9uICgpIHsKICAgIC8vRXhwZWN0cyBhIGJvb2xlYW4gZmlyc3QsIHRoZW4gYW4gYXJiaXRyYXJ5LWxlbmd0aCBsaXN0IG9mIHN0cmluZ3MKICAgIC8vdG8gY29tYmluZS4gQm9vbGVhbiBkZXRlcm1pbmVzIG9yZGVyLgogICAgY29uc3QgY29tYmluZVN0cmluZ3MgPSBmdW5jdGlvbiAodmFsczogQXJyYXk8YW55PikgewogICAgICBjb25zdCByZXZlcnNlT3JkZXIgPSB2YWxzWzBdOwogICAgICB2YWxzID0gcmV2ZXJzZU9yZGVyID8gdmFscy5zaGlmdCgpLnJldmVyc2UoKSA6IHZhbHMuc2hpZnQoKTsKICAgICAgCiAgICAgIGxldCBvdXRTdHJpbmcgPSAiIgogICAgICB2YWxzLmZvckVhY2goKHZhbCkgPT4gewogICAgICAgIG91dFN0cmluZyArPSB2YWw7CiAgICAgIH0pOwogICAgICByZXR1cm4gW291dFN0cmluZ107CiAgICB9OwogIAogICAgcmV0dXJuIHsgZnVuY01hcDogeyAiY29tYmluZVN0cmluZ3MiOiBjb21iaW5lU3RyaW5ncyB9IH07CiAgfSkoKTs=",
                "language": "javascript"
            }
        }
    ],
    "inputOutputValues": [
        {
            "meta": {
                "uuid": "08fd2f58-9f16-4864-be4c-5a508afd7e08",
                "name": "Word_1"
            },
            "data": "One"
        },
        {
            "meta": {
                "uuid": "c424d96a-c33c-4d35-bf31-bd0eddbf0ec9",
                "name": "Word_2"
            },
            "data": "Two"
        },
        {
            "meta": {
                "uuid": "bcc5cf31-b331-4de8-82d1-ea656c0961f0",
                "name": "Word_12"
            },
            "data": ""
        },
        {
            "meta": {
                "uuid": "9d621de0-b56e-4ab1-ace0-6fdab7b3e654",
                "name": "Word_3"
            },
            "data": "Three"
        },
        {
            "meta": {
                "uuid": "c464d0b9-6cd0-4198-b6ab-79c3bd7b27f9",
                "name": "Word_4"
            },
            "data": "Four"
        },
        {
            "meta": {
                "uuid": "da30c2db-4ee6-49de-85d4-e53a2cdcd44d",
                "name": "Word_34"
            },
            "data": ""
        },
        {
            "meta": {
                "uuid": "3756b8f4-03a5-4e9c-9dcd-05557593bb39",
                "name": "Word_1234"
            },
            "data": ""
        },
        {
            "meta": {
                "uuid": "32e271b2-29b1-47ab-b896-68109b50cf8d",
                "name": "Bool_Word12"
            },
            "data": false
        },
        {
            "meta": {
                "uuid": "1b3fb9e7-a687-45ff-85d5-6509af926e28",
                "name": "Bool_Word34"
            },
            "data": false
        },
        {
            "meta": {
                "uuid": "7ad959dd-79cb-446e-86c3-541a237c48f0",
                "name": "Bool_Word1234"
            },
            "data": false
        }
    ],
    "diagrams": [
        {
            "meta": {
                "uuid": "219b3be3-94e6-4167-9a2b-ae65fd16c4af",
                "name": "CDD",
                "createdDate": "2025-03-17T08:33:30-04:00"
            },
            "elements": [
                {
                    "meta": {
                        "uuid": "2692d043-ca34-4fd7-8bd7-47a9c52d22b2",
                        "name": "Reverse Order?",
                        "summary": "(For Word 1+2)"
                    },
                    "causalType": "External",
                    "position": {
                        "x": 510,
                        "y": 250
                    },
                    "displays": [
                        {
                            "meta": {
                                "uuid": "5a52e7bc-0749-482e-acd6-8ce93cb41cf1"
                            },
                            "displayType": "controlBoolean",
                            "content": {
                                "controlParameters": {
                                    "value": false,
                                    "isInteractive": true
                                }
                            }
                        }
                    ]
                },
                {
                    "meta": {
                        "uuid": "8c25dcf2-75c2-4294-83c3-d00cee8830ad",
                        "name": "Word 2"
                    },
                    "causalType": "Lever",
                    "position": {
                        "x": 210,
                        "y": 200
                    },
                    "displays": [
                        {
                            "meta": {
                                "uuid": "668f432c-13ce-48cf-9cbe-a4091f9632fa"
                            },
                            "displayType": "controlText",
                            "content": {
                                "controlParameters": {
                                    "value": "",
                                    "isInteractive": true
                                }
                            }
                        }
                    ]
                },
                {
                    "meta": {
                        "uuid": "43d3cd2c-d774-4a83-9720-77432c54c8cb",
                        "name": "Word 1"
                    },
                    "causalType": "Lever",
                    "position": {
                        "x": 210,
                        "y": 130
                    },
                    "displays": [
                        {
                            "meta": {
                                "uuid": "11f99fc9-8a64-4a0f-8460-6dc96684c8f6"
                            },
                            "displayType": "controlText",
                            "content": {
                                "controlParameters": {
                                    "value": "",
                                    "isInteractive": true
                                }
                            }
                        }
                    ]
                },
                {
                    "meta": {
                        "uuid": "2e86b7af-1004-4269-9d63-7ab21ace8cf1",
                        "name": "Reverse Order?",
                        "summary": "(For Word 3+4)"
                    },
                    "causalType": "External",
                    "position": {
                        "x": 510,
                        "y": 500
                    },
                    "displays": [
                        {
                            "meta": {
                                "uuid": "b3e9e1b2-b86a-4335-b3f7-483d50eaff57"
                            },
                            "displayType": "controlBoolean",
                            "content": {
                                "controlParameters": {
                                    "value": false,
                                    "isInteractive": true
                                }
                            }
                        }
                    ]
                },
                {
                    "meta": {
